"""Regenerate the app icons from static/img/app-icon.svg.

    python tools/build_icons.py

app-icon.svg is the single source of truth. Everything else in static/img is
generated from it and should not be hand-edited:

    app-icon-mark.svg    puppy only, scaled to fill — the small-size variant
    app-icon-512.png     PWA / install prompt
    app-icon-192.png     PWA / Android home screen
    apple-touch-icon.png iOS home screen (180px, no SVG support there)
    favicon-32.png       browser tab
    favicon-16.png       browser tab
    favicon.ico          legacy / Windows pinned sites

Rasterizing is done by screenshotting the SVG in headless Edge or Chrome —
there is no cairo/rsvg binding installed. Every size is rendered at 1024 and
downsampled with LANCZOS so the antialiasing stays clean. The 16/32 sizes come
from the simplified mark: at a tab's size the growth line is only noise.
"""
import os
import re
import subprocess
import sys
import time

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMG = os.path.join(ROOT, "static", "img")
SRC = os.path.join(IMG, "app-icon.svg")
TMP = os.path.join(IMG, ".build")

BROWSERS = [
    r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
    r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
    r"C:\Program Files\Google\Chrome\Application\chrome.exe",
    r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
    "/usr/bin/google-chrome",
    "/usr/bin/chromium",
]

GENERATED = "<!-- GENERATED by tools/build_icons.py from app-icon.svg. Do not edit. -->\n"


def find_browser():
    for path in BROWSERS:
        if os.path.exists(path):
            return path
    sys.exit("No Edge/Chrome found to rasterize with; add its path to BROWSERS.")


def render(browser, svg_text, tag, px=1024):
    """Screenshot svg_text at px x px and return it as an RGBA image."""
    os.makedirs(TMP, exist_ok=True)
    page = os.path.join(TMP, f"page-{tag}.html")
    shot = os.path.join(TMP, f"{tag}.png")
    if os.path.exists(shot):
        os.remove(shot)
    with open(page, "w", encoding="utf-8") as fh:
        fh.write("<style>html,body{margin:0;padding:0;background:transparent}"
                 f"svg{{display:block;width:{px}px;height:{px}px}}</style>" + svg_text)
    subprocess.run(
        [browser, "--headless=new", "--disable-gpu", "--hide-scrollbars",
         "--default-background-color=00000000", "--force-device-scale-factor=1",
         f"--screenshot={shot}", f"--window-size={px},{px}",
         "file:///" + page.replace("\\", "/")],
        check=True, capture_output=True)
    for _ in range(60):                     # the screenshot lands after exit
        if os.path.exists(shot) and os.path.getsize(shot):
            break
        time.sleep(0.5)
    if not os.path.exists(shot):
        sys.exit(f"{browser} produced no screenshot for {tag}")
    return Image.open(shot).convert("RGBA")


def derive_mark(full):
    """The small-size variant, used for the browser-tab favicons.

    A 16px favicon is about 1/32nd the area the home-screen icon gets, and
    the full drawing does not survive the trip: the paws, toe lines, fur
    strokes and cowlick each collapse to roughly one pixel of mud, and
    together they smear the face they surround into a brown blob. So the mark
    keeps only what still reads at a tab's size — the ears, the fluffy crown,
    the eyes, the nose and the muzzle — and frames on the head, since the
    safe-area padding a launcher icon needs is the first thing worth spending
    at this size.

    Everything droppable is tagged class="fine" in app-icon.svg, so this
    function decides *how small is too small* and the artwork decides *what
    counts as fine detail*. Adding another flourish there needs no change here.
    """
    # Self-closing <path class="fine" .../> and <ellipse class="fine" .../>,
    # plus leaf <g class="fine">…</g> groups. None of them nest, so a
    # non-greedy match is safe.
    mark = re.sub(r' *<(?:path|ellipse) class="fine".*?/>\n', "", full, flags=re.S)
    mark = re.sub(r' *<g class="fine".*?</g>\n', "", mark, flags=re.S)
    if 'class="fine"' in mark:
        sys.exit("derive_mark() left a class=\"fine\" element behind; check app-icon.svg.")
    if mark.count("<path") < 4:
        sys.exit("derive_mark() stripped too much of app-icon.svg.")

    # Reframe on the head. The full icon centres the whole lying-down dog
    # (paws included) at y=328; with the paws gone the head alone spans
    # roughly y=163..458, so the mark centres on y=310 and scales up to fill.
    old = 'transform="translate(256,256) scale(0.9) translate(-256,-328)"'
    new = 'transform="translate(256,256) scale(1.16) translate(-256,-310)"'
    if old not in mark:
        sys.exit("app-icon.svg no longer has the transform derive_mark() replaces.")
    return mark.replace(old, new)


def main():
    browser = find_browser()
    full = open(SRC, encoding="utf-8").read()
    mark = derive_mark(full)

    with open(os.path.join(IMG, "app-icon-mark.svg"), "w", encoding="utf-8") as fh:
        fh.write(GENERATED + mark)

    big = render(browser, full, "full")
    small = render(browser, mark, "mark")

    for size, name in [(512, "app-icon-512.png"), (192, "app-icon-192.png"),
                       (180, "apple-touch-icon.png")]:
        big.resize((size, size), Image.LANCZOS).save(os.path.join(IMG, name))
    for size, name in [(32, "favicon-32.png"), (16, "favicon-16.png")]:
        small.resize((size, size), Image.LANCZOS).save(os.path.join(IMG, name))
    # Legacy .ico only needs the small sizes — the PNG/SVG links cover the rest.
    small.resize((64, 64), Image.LANCZOS).save(
        os.path.join(IMG, "favicon.ico"), sizes=[(16, 16), (32, 32), (48, 48)])

    for stale in os.listdir(TMP):
        os.remove(os.path.join(TMP, stale))
    os.rmdir(TMP)
    print("icons written to static/img")


if __name__ == "__main__":
    main()
